development: &defaults
  sessions: true
  logging: true
  static: true
  app_path: "/"
  assets_url_base: "//assets.malmo.se/internal/3.0/"
  autocomplete_url: "http://malmo.appliance.siteseeker.se/qc/webb/qc"
  search_account: "malmo"
  search_index: "webb"
  cache_ttl: 1
  max_age: 0

test:
  <<: *defaults
  show_exceptions: false
  cache_ttl: 43200
  max_age: 14400

production:
  <<: *defaults
  show_exceptions: false
  cache_ttl: 43200
  max_age: 14400

