analysis:
  analyzer:
    term_index:
      tokenizer: edge_ngram_2
      filter:
      - lowercase
      char_filter:
      - hyphen
    term_search:
      tokenizer: keyword
      filter:
      - lowercase
      char_filter:
      - hyphen_space
  tokenizer:
    edge_ngram_2:
      type: edgeNGram
      min_gram: 2
      max_gram: 50
      token_chars:
      - letter
      - digit
      - symbol
      - punctuation
  char_filter:
    hyphen_space:
      type: pattern_replace
      pattern: "[-,\\s]"
      replacement: ''
    hyphen:
      type: pattern_replace
      pattern: "[-]"
      replacement: ''
