analysis:
  analyzer:
    term_index:
      tokenizer: ngram_2
      filter:
      - lowercase
      - asciifolding
    term_search:
      tokenizer: keyword
      filter:
      - asciifolding
      - lowercase
  tokenizer:
    ngram_2:
      type: nGram
      min_gram: 2
      max_gram: 50
      token_chars:
      - letter
      - digit
      - whitespace
